### ISSUE TITLE
关于登录状态保存的两个问题

### ISSUE THREAD

**Issue by mio-hu** [lihuacai168/playwright_demo#1]
你好🥦
1. 我看到你在创建上下文的时候用了storage_state，但是没有找到存储的代码
![image](https://github.com/lihuacai168/playwright_demo/assets/50364347/c47dc1e0-9feb-4d84-ae8e-d6787f60a1ca)
2. 还有就是你在conftest.py文件里面定义了auth_page方法目的就是为了使用storage_state鉴权方便吗？还是还有其他的作用

**Comment by lihuacai168** [comment]
> 你好🥦
> 
> 1. 我看到你在创建上下文的时候用了storage_state，但是没有找到存储的代码
>    ![image](https://private-user-images.githubusercontent.com/50364347/320271179-c47dc1e0-9feb-4d84-ae8e-d6787f60a1ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDQ0NTUsIm5iZiI6MTcxMjUwNDE1NSwicGF0aCI6Ii81MDM2NDM0Ny8zMjAyNzExNzktYzQ3ZGMxZTAtOWZlYi00ZDg0LWFlOGUtZDY3ODdmNjBhMWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE1MzU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YWI3OWQ5MjVjODQ2ZWYzNWU1MzliYzcxNTM1YjZjNTExYTUzNzczNjBiZGY1MTNiMGRjODNlZDY3ZTdiZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.57skG0dgd31lbUDXVkzIq0lWWfgtqmgCad8kussrfEE)
> 2. 还有就是你在conftest.py文件里面定义了auth_page方法目的就是为了使用storage_state鉴权方便吗？还是还有其他的作用

这里主要是为了本地鉴权用的，没有储存的代码，意思指的是没有生成auth.json的代码吗？
这个我没有实现，本地调试直接写入即刻。跑自动化时，可以通过调用接口来生成。

**Comment by mio-hu** [comment]
> > 你好🥦
> > 
> > 1. 我看到你在创建上下文的时候用了storage_state，但是没有找到存储的代码
> >    ![image](https://private-user-images.githubusercontent.com/50364347/320271179-c47dc1e0-9feb-4d84-ae8e-d6787f60a1ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDQ0NTUsIm5iZiI6MTcxMjUwNDE1NSwicGF0aCI6Ii81MDM2NDM0Ny8zMjAyNzExNzktYzQ3ZGMxZTAtOWZlYi00ZDg0LWFlOGUtZDY3ODdmNjBhMWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE1MzU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YWI3OWQ5MjVjODQ2ZWYzNWU1MzliYzcxNTM1YjZjNTExYTUzNzczNjBiZGY1MTNiMGRjODNlZDY3ZTdiZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.57skG0dgd31lbUDXVkzIq0lWWfgtqmgCad8kussrfEE)
> > 2. 还有就是你在conftest.py文件里面定义了auth_page方法目的就是为了使用storage_state鉴权方便吗？还是还有其他的作用
> 
> 这里主要是为了本地鉴权用的，没有储存的代码，意思指的是没有生成auth.json的代码吗？ 这个我没有实现，本地调试直接写入即刻。跑自动化时，可以通过调用接口来生成。

了解感谢回复
